services:
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"
    networks:
      - n8n_evoapi

  postgres:
    image: pgvector/pgvector:pg17
    platform: linux/amd64
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - n8n_evoapi

  chatwoot:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"  # Expondo porta para acesso local
    volumes:
      - chatwoot_data:/app/storage
    command: bundle exec rails s -b 0.0.0.0
    networks:
      - n8n_evoapi
  chatwoot-sidekiq:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot_sidekiq
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
    networks:
      - n8n_evoapi
    volumes:
      - chatwoot_data:/app/storage

  evolution-api:
    image: atendai/evolution-api:v1.7.1  # Versão estável da Evolution API
    container_name: evolution-api
    restart: always
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - CORS_ORIGIN=*
      - DEL_INSTANCE=false
      - DATABASE_ENABLED=false  # Desabilitando banco temporariamente
      - REDIS_ENABLED=true
      - REDIS_URI=redis://:default@redis:6379
      - RABBITMQ_ENABLED=false
      - WEBSOCKET_ENABLED=false
      - CONFIG_SESSION_PHONE_CLIENT=Evolution API
      - CONFIG_SESSION_PHONE_NAME=Chrome
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    depends_on:
      - redis
    networks:
      - n8n_evoapi

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    platform: linux/amd64
    environment:
      - WEBHOOK_URL=http://localhost:5678
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_LOG_LEVEL=debug
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=default
      - DB_POSTGRESDB_USER=default
      - DB_POSTGRESDB_PASSWORD=default
      - N8N_METRICS=true
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - postgres
    networks:
      - n8n_evoapi

volumes:
  pgdata:
  n8n_data:
  chatwoot_data:
  evolution_instances:
  evolution_store:

networks:
  n8n_evoapi:
    driver: bridge
